name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - client/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Create .env File
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
        working-directory: ./client

      - name: Build Vue App
        run: npm run build
        working-directory: ./client
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
          publish_branch: gh-pages
